services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - node-app

  node-app:
    build:
      context: .
      target: base
    env_file:
      - ./.env
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    user: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local
