services:
  nginx:
    ports:
      - "80:80"
    build:
      target: prod
  node-app:
    build:
      context: .
      target: prod
    env_file:
      - ./.env
    ports:
      - "8080:8080"
  postgres:
    ports:
      - "5432:5432"
